#!/bin/bash
#SBATCH --job-name=SWE_otf_1tomany
#SBATCH --output=%x.o%j
#SBATCH --error=%x.e%j
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu
#SBATCH --mem=16G
#SBATCH --time=12:00:00

module load miniconda3
source "$CONDA_PREFIX/etc/profile.d/conda.sh" 
conda activate swe-cv-pytorch

cd ..
python -u train_otf_1tomany.py -root ../datasets/arda/ -image_size 768 -out_channels 3 -f 4
